# Define the target document name (without extension)
TARGET = paper

# Define auxiliary files generated by LaTeX that you want to clean
AUXFILES = $(TARGET).aux $(TARGET).log $(TARGET).out $(TARGET).toc $(TARGET).lof $(TARGET).lot $(TARGET).bbl $(TARGET).blg $(TARGET).fls $(TARGET).fdb_latexmk $(TARGET).synctex.gz $(TARGET).bcf $(TARGET).aux.bbl $(TARGET).aux.blg $(TARGET).run.xml

# Define the TeX engine to use (pdflatex, xelatex, lualatex)
LATEX = pdflatex

# Rule for compiling the .tex file
all:
	rm -f $(AUXFILES)
	$(LATEX) $(TARGET).tex
	bibtex $(TARGET)
	bibtex $(TARGET)
	$(LATEX) $(TARGET).tex
	$(LATEX) $(TARGET).tex

# Rule for deep clean (including PDF file)
clean:
	rm -f $(AUXFILES)

.PHONY: all clean

